name: Run News Scraper Daily

on:
  schedule:
    - cron: '0 6 * * *'  # รันทุกวันตอน 6:00 AM UTC
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp requests beautifulsoup4 transformers torch

      - name: Run scraper
        run: |
          python news_scraper.py
